controller_list:
  - name: forearm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - base_forearm_joint
      - forearm_0_1_joint